name: Fix PHP code style
run-name: Fixing style on ${{ github.ref_name }}
on:
  push:
    paths:
      - "**.php"

jobs:
  pint-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix styling"

